### ISSUE TITLE
Cannot add plugin from Gradle plugin repository

### ISSUE THREAD

**Issue by al3xand3r-K** [assertj/assertj-generator-gradle-plugin#12] opened 2017-12-04 11:35 UTC
```
$ ./gradlew --version
Gradle 4.3.1
Groovy:       2.4.12
...
```
Applying plugin as shown [here](https://plugins.gradle.org/plugin/org.assertj.generator) results in an error upon importing changes to `build.gradle`. The only difference with that example is that I also have `jcenter()` applied.
```
Error:Could not find gradle.plugin.org.assertj:assertj-generator-gradle-plugin:0.0.5.
Searched in the following locations:
    https://plugins.gradle.org/m2/gradle/plugin/org/assertj/assertj-generator-gradle-plugin/0.0.5/assertj-generator-gradle-plugin-0.0.5.pom
    https://plugins.gradle.org/m2/gradle/plugin/org/assertj/assertj-generator-gradle-plugin/0.0.5/assertj-generator-gradle-plugin-0.0.5.jar
    https://jcenter.bintray.com/gradle/plugin/org/assertj/assertj-generator-gradle-plugin/0.0.5/assertj-generator-gradle-plugin-0.0.5.pom
    https://jcenter.bintray.com/gradle/plugin/org/assertj/assertj-generator-gradle-plugin/0.0.5/assertj-generator-gradle-plugin-0.0.5.jar
Required by:
    project :
```
@Nava2 could you please check if the plugin is published?

**Comment by Nava2** [comment] 2017-12-04 12:18
Hmm, if the gradle repo site has those instructions, its generating them from the published version. 

Could you create a minimum example via a simple repo to reproduce this? I'm strapped for time these days and appreciate the help.

**Comment by menya84** [comment] 2017-12-11 15:07
The problem is that pom file is corrupted in maven repo, please upload correct artifacts.
Look here https://plugins-artifacts.gradle.org/gradle.plugin.org.assertj/assertj-generator-gradle-plugin/0.0.5/82c52e4b3f962798e9851fcf7d1dcac1929f822faca8ea8a30139887932772d0/assertj-generator-gradle-plugin-0.0.5.pom

**Comment by Nava2** [comment] 2018-03-01 13:51
@menya84 I'm very sorry for not getting back to this sooner.

I think there's an issue with how I'm trying to publish the plugins. Unfortunately, I don't have the Gradle plugin keys locally so I'll need to get ahold of @joel-costigliola to see if I can get those keys back. 

I uploaded a new version, v0.0.6 and it still can't download the plugins -- the repository is giving bad results. See here: https://plugins.gradle.org/m2/gradle/plugin/org/assertj/assertj-generator-gradle-plugin/0.0.6/. My larger concern is that the publish step on travis is [successful](https://travis-ci.org/assertj/assertj-generator-gradle-plugin/jobs/347765852). 

I found [this gradle forums thread](https://discuss.gradle.org/t/published-plugin-not-found-404/23565/6) and have updated the publishing plugin. I need to go to work now, but I'll verify this works later tonight.

**Comment by Nava2** [comment] 2018-03-01 13:56
@menya84 @tomyy updating to v0.0.6b seems to work 🎉! Please close this issue if you can verify this, either of you.

**Comment by tomyy** [comment] 2018-03-01 21:16
@Nava2 for me it works too. Before closing I would wait for the feedback from @menya84

**Comment by Nava2** [comment] 2018-03-06 00:27
Going to close as the issue appears to be fixed.

**Closed by Nava2** 2018-03-06 00:27 UTC
